# generator/tasks/main.yml
---
- name: Create the generator directory
  file: path=~/youxia-generator/target/ owner=ubuntu group=ubuntu mode=0755 state=directory

- name: Copy the jar file
  get_url:
    dest=~/youxia-generator/target/youxia-generator-{{ youxia_version }}-jar-with-dependencies.jar
    url=https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/io/cloudbindle/youxia-generator/{{ youxia_version }}/youxia-generator-{{ youxia_version }}-jar-with-dependencies.jar
    mode=755
