# tagger/tasks/main.yml
---
- name: Create the tagger/common directory
  file: path=~/youxia-common/target/ owner=ubuntu group=ubuntu mode=0755 state=directory

- name: Copy the jar file
  get_url:
    dest=~/youxia-common/target/youxia-common-{{ youxia_version }}-jar-with-dependencies.jar
    url=https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/io/cloudbindle/youxia-common/{{ youxia_version }}/youxia-common-{{ youxia_version }}-jar-with-dependencies.jar
    mode=755
