notifications:
  slack: oicr:S9k4EowgQv9AnbCfEZHSzCsg

sudo: false
language: java
jdk: 
  - oraclejdk8

script: mvn -B clean install -DskipITs=false

after_success:
  - mvn -B clean -DskipITs=false cobertura:cobertura cobertura:cobertura-integration-test coveralls:report
