---
- hosts: all 
  sudo: True
  tasks:

  - name: Set hostname
    hostname: name={{ansible_hostname}}

  # fix up hostname --fqdn call needed for JUnique library
  - name: Build hosts file entry for hostname
    lineinfile: dest=/etc/hosts line="127.0.0.1 {{ansible_hostname}}" state=present
    with_items: groups['all']

  # Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
  # Will include all hosts the playbook is run on.
  # Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html
  - name: Build hosts file for all hosts
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']

- hosts: sensu-server 
  sudo: True
  roles: 
    - { role: server-dependencies }
    - { role: base }
    - { role: server }

- hosts: sensu-client 
  sudo: True
  roles: 
    - { role: base }
    - { role: client }

- hosts: sensu-server
  sudo: True
  roles:
    - { role: uchiwa }

