---
- name: Install uchiwa 
  apt: name=uchiwa state=latest

- name: Template over rabbit connector config
  template: src=uchiwa.json.j2 dest=/etc/sensu/uchiwa.json owner=uchiwa

- name: Enable service
  service: name=uchiwa state=started enabled=yes
