# generator/tasks/main.yml
---
- name: Create the generator directory
  file: path=~/youxia-decider/target/ owner=ubuntu group=ubuntu mode=0755 state=directory

- name: Copy the jar file
  get_url:
    dest=~/youxia-decider/target/youxia-decider-{{ youxia_version }}-jar-with-dependencies.jar
    url=https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/io/cloudbindle/youxia-decider/{{ youxia_version }}/youxia-decider-{{ youxia_version }}-jar-with-dependencies.jar
    mode=755
