# client/tasks/main.yml
---
- name: Template over sensu config
  template: src=client.json.j2 dest=/etc/sensu/conf.d/client.json
  notify: restart sensu-client

- name: Install rubygems
  apt: name=rubygems state=latest
  when: ansible_distribution_release == "precise"

- name: Install ruby
  apt: name=ruby state=latest
  when: ansible_distribution_release == "trusty"

- name: Install sensu-plugin gem
  gem: name=sensu-plugin state=latest
  when: ansible_distribution_release == "precise"

- name: Install ruby-dev
  apt: name=ruby-dev state=latest

- name: Install packages needed to build sensu plugins
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libpq-dev

- name: Install sensu plugins (and some of their dependencies)
  gem: name={{ item }} state=latest user_install=no
  with_items:
    - sys-filesystem
    - rake
    - bundler
    - pg
    - rest_client
    - sensu-plugins-postgres
    - sensu-plugins-rabbitmq
    - sensu-plugins-disk-checks
    - sensu-plugins-process-checks
    - sensu-plugins-load-checks
    - sensu-plugins-memory-checks
    - sensu-plugins-network-checks
    - sensu-plugins-io-checks
    - sensu-plugins-ntp
    - sensu-plugins-cpu-checks
    - sensu-plugins-filesystem-checks
    - sensu-plugins-disk-checks
  notify: restart sensu-client

- name: Activate client services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - sensu-client 
