---
# file: roles/java/tasks/cloudera.yml
- name: Java | Get Java
  get_url:
    dest: '/tmp/oracle-j2sdk1.7_1.7.0+update25-1_amd64.deb'
    url: 'http://archive.cloudera.com/cm5/ubuntu/lucid/amd64/cm/pool/contrib/o/oracle-j2sdk1.7/oracle-j2sdk1.7_1.7.0+update25-1_amd64.deb'

- name: Java | Install Java
  command: dpkg --skip-same-version -i /tmp/oracle-j2sdk1.7_1.7.0+update25-1_amd64.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"

- name: Java | Set up Java
  command: 'update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-7-oracle-cloudera/jre/bin/java 2000'
  when: dpkg_result.changed

- name: Java | Set up Java
  command: 'update-alternatives --set java /usr/lib/jvm/java-7-oracle-cloudera/jre/bin/java'
  when: dpkg_result.changed
  
- name: Java | Set up Jar
  command: 'update-alternatives --install /usr/bin/jar jar /usr/lib/jvm/java-7-oracle-cloudera/bin/jar 2000'
  when: dpkg_result.changed

- name: Java | Set up Jar
  command: 'update-alternatives --set jar /usr/lib/jvm/java-7-oracle-cloudera/bin/jar'
  when: dpkg_result.changed

- name: Java | Set JAVA_HOME
  lineinfile: 
    line: 'JAVA_HOME=/usr/lib/jvm/java-7-oracle-cloudera'
    dest: /etc/environment
    state: present
    create: yes


